"""empty message

Revision ID: f5cd59844aed
Revises: 
Create Date: 2019-08-13 20:26:41.644956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5cd59844aed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log') as batch_op:
        batch_op.alter_column('active_users',
                existing_type=sa.BIGINT(),
                nullable=False)
        batch_op.alter_column('currency_sentiment',
                existing_type=sa.BIGINT(),
                nullable=False)
        batch_op.alter_column('id',
                existing_type=sa.BIGINT(),
                nullable=False,
                autoincrement=True)
        batch_op.alter_column('subreddit',
                existing_type=sa.TEXT(),
                nullable=False)
        batch_op.alter_column('subreddit_sentiment',
                existing_type=sa.FLOAT(),
                nullable=False)
        batch_op.create_index(op.f('ix_log_timestamp'), ['timestamp'], unique=False)
        batch_op.drop_index('ix_log_index')
        batch_op.drop_column('index')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('index', sa.BIGINT(), nullable=True))
    op.create_index('ix_log_index', 'log', ['index'], unique=False)
    op.drop_index(op.f('ix_log_timestamp'), table_name='log')
    op.alter_column('log', 'subreddit_sentiment',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('log', 'subreddit',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('log', 'id',
               existing_type=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.alter_column('log', 'currency_sentiment',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('log', 'active_users',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
